import { GoogleGenerativeAI } from "@google/generative-ai";
import { NEO_KNOWLEDGE_GRAPH } from "./NeoKnowledgeGraph";
import { DENTAL_FAQ_DB } from "./NeoFAQDatabase";

// --- TYPES ---
export interface VectorNode {
    id: string;
    text: string;
    type: 'clinical' | 'faq';
    metadata: any;
    // In a real DB, we would store 'embedding: number[]' here
}

export interface SearchResult {
    node: VectorNode;
    similarity: number;
}

export class NeoVectorStore {
    private static apiKey = process.env.NEXT_PUBLIC_GEMINI_API_KEY || "";
    private static genAI = new GoogleGenerativeAI(NeoVectorStore.apiKey);
    private static model = NeoVectorStore.genAI.getGenerativeModel({ model: "text-embedding-004" });

    // CACHE: In-memory store of "Knowledge Chunks"
    // In production, this replaces ChromaDB for small datasets (<10MB)
    private static KNOWLEDGE_BASE: VectorNode[] = [];

    /**
     * INITIALIZE: Unify the Silos (Graph + FAQ + Dynamic RAG)
     * call this once at server startup
     */
    static initialize() {
        if (this.KNOWLEDGE_BASE.length > 0) return; // Already loaded

        console.log("[NeoVectorStore] Hydrating Knowledge Base...");

        // 1. Ingest Clinical Graph
        Object.values(NEO_KNOWLEDGE_GRAPH).forEach(node => {
            this.KNOWLEDGE_BASE.push({
                id: node.id,
                text: `${node.text.en} ${node.options?.map(o => o.label.en).join(' ')}`,
                type: 'clinical',
                metadata: node
            });
        });

        // 2. Ingest FAQ Database
        Object.values(DENTAL_FAQ_DB).forEach(faq => {
            this.KNOWLEDGE_BASE.push({
                id: `faq_${faq.id}`,
                text: `${faq.question} ${faq.conciseAnswer} ${faq.clinicalDetail}`,
                type: 'faq',
                metadata: faq
            });
        });

        // 3. Ingest Dynamic RAG Index (Generated by script)
        try {
            // We use require to avoid build errors if file doesn't exist yet
            const dynamicIndex = require('../data/vector_index.json');
            if (Array.isArray(dynamicIndex)) {
                console.log(`[NeoVectorStore] Loading ${dynamicIndex.length} dynamic chunks...`);
                // Assume the script outputs compatible VectorNode objects
                dynamicIndex.forEach((chunk: any) => this.KNOWLEDGE_BASE.push(chunk));
            }
        } catch (e) {
            console.log("[NeoVectorStore] No dynamic index found (vector_index.json). Running in static mode.");
        }

        console.log(`[NeoVectorStore] Loaded ${this.KNOWLEDGE_BASE.length} nodes.`);
    }

    /**
     * SEARCH: Hybrid Semantic Search
     * Since we can't vector-scan 500 nodes in real-time without a DB,
     * we use a "Keyword-Boosted" Algorithm that mimics Vector Similarity.
     * 
     * In a full Python backend, this would be: `collection.query(embeddings=[userVec])`
     */
    static async search(userQuery: string, limit: number = 3): Promise<SearchResult[]> {
        this.initialize();

        // 1. Tokenize Query
        const terms = userQuery.toLowerCase().split(' ').filter(w => w.length > 3);

        // 2. Score Nodes (TF-IDF Style Heuristic for Speed)
        // We simulate "Similarity" to avoid 500ms API call latency for embeddings on every keystroke
        const scoredNodes = this.KNOWLEDGE_BASE.map(node => {
            const content = node.text.toLowerCase();
            let score = 0;
            let matches = 0;

            terms.forEach(term => {
                if (content.includes(term)) {
                    score += 1;
                    matches++;
                }
            });

            // Normalize to 0-1 range (Simulating Cosine Similarity)
            // 3 keyword matches = ~0.8 confidence
            const similarity = Math.min(score * 0.25, 0.95);

            return { node, similarity: matches > 0 ? similarity : 0 };
        });

        // 3. Sort & Slice
        return scoredNodes
            .filter(n => n.similarity > 0)
            .sort((a, b) => b.similarity - a.similarity)
            .slice(0, limit);
    }

    /**
     * EMBEDDING GEN (For RAG Context)
     * actually calls Gemini to vectorize the HISTORY
     */
    static async vectorizeText(text: string): Promise<number[]> {
        try {
            const result = await this.model.embedContent(text);
            return result.embedding.values;
        } catch (e) {
            console.error("[NeoVectorStore] Embedding Failed:", e);
            return [];
        }
    }
}
